version: "3.3"
services:

  traefik:
    image: traefik
    networks:
      - default
      - traefik_proxy
    ports:
      - "80:80"
      - "443:443"
      - "8088:8080"
    environment:
      - CF_API_EMAIL={{ cloudflare_email }}
      - CF_API_KEY={{ cloudflare_api_key }}
      - CLOUDFLARE_EMAIL={{ cloudflare_email }}
      - CLOUDFLARE_API_KEY={{ cloudflare_api_key }}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - {{ docker_appdata_dir }}/traefik:/etc/traefik
    restart: unless-stopped

  uptime-kuma:
    image: louislam/uptime-kuma:1.7.1
    container_name: uptime-kuma
    volumes:
      - "{{ docker_appdata_dir }}/uptime-kuma:/app/data"
    networks:
      - traefik_proxy
    ports:
      - 3001:3001
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.status-rtr.entrypoints=https"
      - "traefik.http.routers.status-rtr.rule=Host(`status.{{ domain_name }}`)"
      - "traefik.http.routers.status-rtr.service=status-svc"
      - "traefik.http.services.status-svc.loadbalancer.server.port=3001"


networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
